project_name: data-server
builds:
  - id: data-server
    binary: data-server
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
  - id: datactl
    binary: datactl
    main: ./client/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - data-server
      - datactl
    image_templates:
      - "ghcr.io/iptecharch/data-server:latest"
      - "ghcr.io/iptecharch/data-server:v{{ .Version }}"
      - "registry.kmrd.dev/iptecharch/data-server:latest"
      - "registry.kmrd.dev/iptecharch/data-server:v{{ .Version }}"
      - "registry.k8s.hans.io/iptecharch/data-server:latest"
      - "registry.k8s.hans.io/iptecharch/data-server:v{{ .Version }}"
    dockerfile: goreleaser.dockerfile
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/iptecharch/{{.ProjectName}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armv7
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
  draft: true
  replace_existing_draft: true
  disable: false
