coverage:
  status:
    patch:
      default:
        informational: true # don't fail the build if PR coverage is missing
        if_ci_failed: success
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: new
github_checks:
  annotations: false
ignore:
  - "tests/sdcioygot"
  - "mocks"
  - "client"